### ISSUE TITLE
How to get a working implementation of JMEA ?

### ISSUE THREAD

**Issue by RenanBernard** [fang-zhen/Semi-supervised-Heterogeneous-Domain-Adaptation#1]
Hi,

For benchmarking purposes, is it possible to get a working implementation of JMEA mentioned in your paper (the one related to this repo) ? I (and probably others) would be very grateful !

I hope this was a proper way to ask !

Have a nice day.

**Comment by fang-zhen** [comment]
Dear Renan Bernard,

Thank you for your interest on our paper.

After conference  ICLR, we will release our code soon.

The third aurthor implements the JMEA. You can also ask him to this code.

Best Regards,

Zhen
________________________________
发件人: Renan BERNARD ***@***.***>
发送时间: 2022年9月5日 01:14
收件人: fang-zhen/Semi-supervised-Heterogeneous-Domain-Adaptation ***@***.***>
抄送: Subscribed ***@***.***>
主题: [fang-zhen/Semi-supervised-Heterogeneous-Domain-Adaptation] How to get a working implementation of JMEA ? (Issue #1)


Hi,

For benchmarking purposes, is it possible to get a working implementation of JMEA mentioned in your paper (the one related to this repo) ? I (and probably others) would be very grateful !

I hope this was a proper way to ask !

Have a nice day.

―

**Comment by fang-zhen** [comment]
We have updated the code.

Best Regards
